control_panel:
  path: /
  defaults: { _controller: AppBundle:Admin:controlPanel }

configure_initial_profile:
  path: /configure
  defaults: { _controller: AppBundle:Admin:configureInitialProfile }

user_settings:
  path: /settings
  defaults: { _controller: AppBundle:Admin:userSettings }

write_about:
  path: /about
  defaults: { _controller: AppBundle:Admin:writeAbout }

write_article:
  path: /write-article
  defaults: { _controller: AppBundle:Admin:writeArticle }

my_posts:
  path: /my-posts
  defaults: { _controller: AppBundle:Admin:myPosts }

my_articles:
  path: /my-articles
  defaults: { _controller: AppBundle:Admin:myArticles }
