control_panel:
  path: /
  defaults: { _controller: AppBundle:Admin:controlPanel }

configure_initial_profile:
  path: /configure
  defaults: { _controller: AppBundle:Admin:configureInitialProfile }


import_export:
  path: /import-and-export
  defaults: { _controller: AppBundle:Admin:importExport }

change_password:
  path: /settings/change-password
  defaults: { _controller: AppBundle:Admin:changePassword }

download_posts:
  path: /download-posts
  defaults: { _controller: AppBundle:Admin:downloadPosts }

download_post_markdown:
  path: /download-post/{id}
  defaults: { _controller: AppBundle:Admin:downloadPostAsMarkdown }


edit_profile:
  path: /settings/profile
  defaults: { _controller: AppBundle:Admin:editProfile }

edit_social_settings:
  path: /settings/social
  defaults: { _controller: AppBundle:Admin:editSocialSettings }

write_post:
  path: /write-post
  defaults: { _controller: AppBundle:Admin:writeArticle }

edit_post:
  path: /edit-post/{id}
  defaults: { _controller: AppBundle:Admin:editPost }

my_notes:
  path: /my-notes
  defaults: { _controller: AppBundle:Admin:myNotes }

my_articles:
  path: /my-articles
  defaults: { _controller: AppBundle:Admin:myArticles }

rss_feeds:
  path: /feeds
  defaults: { _controller: AppBundle:Admin:feeds }

view_rss_feed:
  path: /feeds/{id}
  defaults: { _controller: AppBundle:Admin:viewRssFeed }

# Hidden actions that don't really have pages associated but should be Protected under the admin firewall
change_post_visibilty_by_id:
  path: /change-visible/{id}
  defaults: { _controller: AppBundle:Post:changePostVisibilityById }

remove_post_by_id:
  path: /remove-post/{id}
  defaults: { _controller: AppBundle:Post:removePostById }

remove_feed_by_id:
  path: /remove-feed/{id}
  defaults: { _controller: AppBundle:Feed:removeFeedById }
