control_panel:
  path: /
  defaults: { _controller: AppBundle:Admin:controlPanel }

configure_initial_profile:
  path: /configure
  defaults: { _controller: AppBundle:Admin:configureInitialProfile }

change_password:
  path: /change-password
  defaults: { _controller: AppBundle:Admin:changePassword }

import_export:
  path: /import-and-export
  defaults: { _controller: AppBundle:Admin:importExport }

edit_profile:
  path: /profile
  defaults: { _controller: AppBundle:Admin:editProfile }

write_post:
  path: /write-post
  defaults: { _controller: AppBundle:Admin:writeArticle }

edit_post:
  path: /edit-post/{id}
  defaults: { _controller: AppBundle:Admin:editPost }

my_notes:
  path: /my-notes
  defaults: { _controller: AppBundle:Admin:myNotes }

my_articles:
  path: /my-articles
  defaults: { _controller: AppBundle:Admin:myArticles }

# Hidden actions that don't really have pages associated but should be Protected under the admin firewall
change_post_visibilty_by_id:
  path: /change-visible/{id}
  defaults: { _controller: AppBundle:Post:changePostVisibilityById }

remove_post_by_id:
  path: /remove-post/{id}
  defaults: { _controller: AppBundle:Post:removePostById }
