index:
  path: /
  defaults: { _controller: AppBundle:Default:index }

admin:
  resource: "@AppBundle/Resources/config/admin_routes.yml"
  prefix: /admin


setup:
  path: /setup
  defaults: { _controller: AppBundle:Registration:register }

login:
    path: /login
    defaults: { _controller: AppBundle:Security:login }

logout:
    path: /logout

# Begin the public facing pages

about:
  path: /about
  defaults: { _controller: AppBundle:Default:about }

list_articles:
  path: /blog
  defaults: { _controller: AppBundle:Default:listArticles  }

view_article:
  path: /blog/{slug}
  defaults: { _controller: AppBundle:Default:viewArticle }

view_post_by_id:
  path: /post/{id}
  defaults: { _controller: AppBundle:Default:viewPostById }
