index:
  path: /
  defaults: { _controller: AppBundle:Default:index }

admin:
  resource: "@AppBundle/Resources/config/admin_routes.yml"
  prefix: /admin


setup:
  path: /setup
  defaults: { _controller: AppBundle:Registration:register }

login:
    path: /login
    defaults: { _controller: AppBundle:Security:login }

logout:
    path: /logout
